name: Update Version on Merge

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Get Current Version
        id: current_version
        run: |
          # Mendapatkan versi saat ini dari file formula
          current_version=$(grep -oP 'version "\K[^\"]+' Formula/flutter_kreasi.rb)
          echo "Current version: $current_version"
          echo "::set-output name=version::$current_version"

      - name: Bump Version
        id: bump_version
        run: |
          # Mengambil versi saat ini, lalu menambahkannya
          version=${{ steps.current_version.outputs.version }}
          new_version=$(echo $version | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo "New version: $new_version"
          echo "::set-output name=new_version::$new_version"

      - name: Update Formula Version
        run: |
          # Mengganti versi di Formula/flutter_kreasi.rb
          sed -i "s/version \".*\"/version \"${{ steps.bump_version.outputs.new_version }}\"/" Formula/flutter_kreasi.rb

          # Update URL download dari GitHub release
          github_url="https://github.com/KreasiMaju/flutter-kreasi/releases/download/${{ steps.bump_version.outputs.new_version }}/flutter_kreasi"
          sed -i "s|url \".*\"|url \"$github_url\"|" Formula/flutter_kreasi.rb

          # Update SHA256 (opsional jika diinginkan hash valid file)
          curl -L "$github_url" -o flutter_kreasi_latest
          sha256=$(sha256sum flutter_kreasi_latest | awk '{ print $1 }')
          sed -i "s/sha256 \".*\"/sha256 \"$sha256\"/" Formula/flutter_kreasi.rb

      - name: Update Print Version
        run: |
          # Mengganti versi di dalam script Formula/flutter_kreasi.rb
          sed -i "s/puts \"Version .*/puts \"Version ${{ steps.bump_version.outputs.new_version }}\"/" Formula/flutter_kreasi.rb

      - name: Configure Git
        run: |
          git config user.name "devry12"
          git config user.email "devrykawiryan@gmail.com"

      - name: Commit changes
        run: |
          git add Formula/flutter_kreasi.rb
          git commit -m "Bump version to ${{ steps.bump_version.outputs.new_version }} and update URL"

      - name: Push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/KreasiMaju/flutter-kreasi.git
          git push origin main

      # Buat GitHub Release secara otomatis menggunakan versi terbaru
      - name: Create GitHub Release
        uses: actions/create-release@v1.1.0
        with:
          tag_name: ${{ env.VERSION }}
          release_name: flutter_kreasi v${{ env.VERSION }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Build Artifact to Release
        run: |
          # Mengupload file flutter_kreasi ke release GitHub
          gh release upload ${{ steps.bump_version.outputs.new_version }} flutter_kreasi_latest
